### ISSUE TITLE
Page Title repeat

### ISSUE THREAD

**Issue by sonjot** [stripeswp/stripes#1]
Hi this theme is supereasy and fast to use and is perfect for what I have been asked to do. I have created a one page website using a single page as the home page. My client is not happy with the way the page title repeats in large red letters. I cannot seem to find a way around this. If I take the page title away it shows on the website. Is there any way to remove the large red heading that repeats the page title or change it? Website is http://lacanianpsychoanalysis.org

Many thanks

**Comment by sonjot** [comment]
Okay I managed to change the title header to be less intrusive by using .... instead of an actual title and by changing the font color to black but ideally I would like the title to disappear altogether on the page that shows as the homepage.
Many thanks

**Comment by stripeswp** [comment]
Under _Appearance_ > _Customize_ > _Custom CSS_, add:

`.home .header{display:none}`

**Comment by sonjot** [comment]
Brilliant, thanks so much

**Comment by stripeswp** [comment]
You're welcome.
