### ISSUE TITLE
transparent masthead conflict

### ISSUE THREAD

**Issue by littlebeeproductions** [stripeswp/stripes#2]
Hi there - I'm using a theme with a transparent nav and this plugin causes the transparent nav to be white instead. It seems to be a style conflict but I can't seem to track it down. Any ideas?

**Comment by webguyio** [comment]
Would it be possible to get the link so that I can take a look?

**Comment by littlebeeproductions** [comment]
sure :) 

http://staging.revelconsulting.com

revel2019_staging
Ax4IA=,#ddH

**Comment by webguyio** [comment]
Found it. Add:

```
.transparent-header #content {
	margin-top: -90px !important;
}
```
