### ISSUE TITLE
color for links in header

### ISSUE THREAD

**Issue by linxeric** [stripeswp/stripes#3]
I'm trying to change the color of the links in the header, but I'm having no luck finding out how to do this, or what customer added CSS I need to use. Can you point me to guidance on how to change these colors for this theme?

**Comment by webguyio** [comment]
```
#menu a {
	color: #09f;
}
```

Paste under _Appearance > Customize > Additional CSS_.

If you're not familiar with color codes, you can select some from here:

https://www.w3schools.com/colors/colors_names.asp

**Comment by linxeric** [comment]
this is great, thanks bhadaway. I did find, however, when I look at the site using a mobile device, then the color changes are not changed, but still on the theme default - so the CSS code you issued does change things on the page viewed from a computer, but not for the mobile devices. Do you need to add other CSS code in order to change those colors? If so, what would that be? Sorry, I should have asked that before, but I assumed those color changes would follow through to the other platforms.

**Comment by webguyio** [comment]
Add additionally:

```
@media( max-width: 768px ) {

	#menu.toggled a, #menu.toggled ul.sub-menu a, #menu.toggled ul.children a {
		color: #09f;
	}

}
```
