### ISSUE TITLE
Change color of the site title and the tagline

### ISSUE THREAD

**Issue by linxeric** [stripeswp/stripes#4]
I'm trying to change the color of the site title and the tagline in the header. What is the CSS to add to change these colors?

**Comment by webguyio** [comment]
```
#site-title a {
	color: #000;
}
```

and

```
#site-description {
	color: #333;
}
```

If you want to learn how to easily view and change styles yourself, I recommend using Firefox:

https://www.mozilla.org/firefox/new/

And then use the Inspector:

https://developer.mozilla.org/docs/Tools/Page_Inspector/How_to/Open_the_Inspector
